# Generated by Django 6.0.2 on 2026-04-20 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='localexperience',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiencemedia',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='experiences.localexperience'),
        ),
        migrations.AddIndex(
            model_name='localexperience',
            index=models.Index(fields=['local', '-created_at'], name='experiences_local_i_e39c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='localexperience',
            index=models.Index(fields=['category'], name='experiences_categor_28944a_idx'),
        ),
        migrations.AddIndex(
            model_name='localexperience',
            index=models.Index(fields=['today_moment_active'], name='experiences_today_m_4628a4_idx'),
        ),
        migrations.AddIndex(
            model_name='localexperience',
            index=models.Index(fields=['created_at'], name='experiences_created_5d3312_idx'),
        ),
    ]
