# Generated by Django 6.0.2 on 2026-04-20 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aithread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiactivity',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aithread'),
        ),
        migrations.AddField(
            model_name='proactivealert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraipreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prefs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aithread',
            index=models.Index(fields=['user', '-updated_at'], name='ai_aithread_user_id_9d4873_idx'),
        ),
        migrations.AddIndex(
            model_name='aiactivity',
            index=models.Index(fields=['thread', 'timestamp'], name='ai_aiactivi_thread__594dff_idx'),
        ),
        migrations.AddIndex(
            model_name='proactivealert',
            index=models.Index(fields=['user', '-created_at'], name='ai_proactiv_user_id_99b979_idx'),
        ),
    ]
