# Generated by Django 6.0.2 on 2026-04-20 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='responders',
            field=models.ManyToManyField(blank=True, help_text='Locals/admins who responded to this alert', related_name='responded_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sosresponse',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sos.sosalert'),
        ),
        migrations.AddField(
            model_name='sosresponse',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['user', '-created_at'], name='sos_sosaler_user_id_c7fc27_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['status'], name='sos_sosaler_status_925a65_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['severity'], name='sos_sosaler_severit_46d07d_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['created_at'], name='sos_sosaler_created_fd8308_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['latitude', 'longitude'], name='sos_sosaler_latitud_081515_idx'),
        ),
        migrations.AddIndex(
            model_name='sosresponse',
            index=models.Index(fields=['alert', '-created_at'], name='sos_sosresp_alert_i_b345c6_idx'),
        ),
        migrations.AddIndex(
            model_name='sosresponse',
            index=models.Index(fields=['responder', '-created_at'], name='sos_sosresp_respond_3edbe3_idx'),
        ),
        migrations.AddIndex(
            model_name='sosresponse',
            index=models.Index(fields=['created_at'], name='sos_sosresp_created_b6f592_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sosresponse',
            unique_together={('alert', 'responder')},
        ),
    ]
