"""
Django settings for kilicare project.
Generated by 'django-admin startproject' using Django 5.2.9.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------
# EXTERNAL API KEYS (From .env)
# -----------------------
# settings.py - REKEBISHA HAPA
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

# Model ya Maandishi pekee (Text)
GROQ_TEXT_MODEL = os.getenv("GROQ_TEXT_MODEL", "llama-3.1-8b-instant")

# Model ya Picha (Vision) - Hapa ndipo uweke jina sahihi
GROQ_VISION_MODEL = os.getenv("GROQ_VISION_MODEL", "llama-3.2-90b-vision-preview")

GROQ_API_URL = os.getenv("GROQ_API_URL", "https://api.groq.com/openai/v1/chat/completions")
WEATHER_API_KEY = os.getenv("WEATHER_API_KEY", "YAKO_API_KEY_HAPA") # Imeongezwa kwa ajili ya AI Tasks

# -----------------------
# SECURITY SETTINGS
# -----------------------
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", 'django-insecure-1yk^7-w!m@9cwx_z(cc5o!ly=b+6#2ghirn-tjxt3bp2yv$d_^')
DEBUG = True
ALLOWED_HOSTS = ['*']

# -----------------------
# APPLICATION DEFINITION
# -----------------------
INSTALLED_APPS = [
    # 1. Daphne lazima iwe juu ya kila kitu kwa ajili ya WebSockets
    'daphne', 
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party Apps
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'channels',
    'graphene_django',
    'graphql_jwt',
    'django_celery_beat', # Imeongezwa kwa ajili ya kuratibu tasks (scheduling)

    # Local Apps (Kilicare+ Modules)
    'users',
    'experiences',
    'messaging.apps.MessagingConfig', # Muhimu kwa ajili ya Signals
    'ai',
    'kilicaremoments',
    'tips',
    'passport',
]

# ASGI / CHANNELS CONFIG
ASGI_APPLICATION = "kilicare.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)], # Default Redis Port
        },
    },
}

# -----------------------
# CELERY CONFIGURATION (Imeongezwa Upya)
# -----------------------
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

AUTH_USER_MODEL = "users.User"

# -----------------------
# MIDDLEWARE
# -----------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Lazima iwe juu kabisa
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS SETTINGS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True 

ROOT_URLCONF = 'kilicare.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kilicare.wsgi.application'

# -----------------------
# REST FRAMEWORK & JWT
# -----------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# -----------------------
# DATABASE (PostgreSQL)
# -----------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'kilicare',
        'USER': 'lastmateru',
        'PASSWORD': 'Gervas03@@',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# PASSWORD VALIDATION
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# -----------------------
# INTERNATIONALIZATION
# -----------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi' 
USE_I18N = True
USE_TZ = True

# -----------------------
# STATIC & MEDIA FILES
# -----------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# GRAPHQL CONFIG
GRAPHENE = {
    "SCHEMA": "kilicare.schema.schema",
    "MIDDLEWARE": [
        "graphql_jwt.middleware.JSONWebTokenMiddleware",
    ],
}

# -----------------------
# EMAIL SETTINGS (Gmail)
# -----------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'materugervas5@gmail.com'
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_APP_PASSWORD", 'kodvtnxtnlrjdkwh') 
DEFAULT_FROM_EMAIL = 'materugervas5@gmail.com'