# Generated by Django 6.0.2 on 2026-03-27 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiactivity',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='aiactivity',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='aiactivity',
            name='input_text',
        ),
        migrations.RemoveField(
            model_name='aiactivity',
            name='output_text',
        ),
        migrations.AddField(
            model_name='aiactivity',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiactivity',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiactivity',
            name='role',
            field=models.CharField(default='user', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aiactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AIThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Mazungumzo Mapya', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='aiactivity',
            name='thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aithread'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProactiveAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAIPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_voice', models.CharField(choices=[('male', 'Kiume'), ('female', 'Kike')], default='female', max_length=10)),
                ('preferred_language', models.CharField(choices=[('sw', 'Kiswahili'), ('en', 'English')], default='sw', max_length=5)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
