# Generated by Django 6.0.2 on 2026-03-30 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_aiactivity_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proactivealert',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='aiactivity',
            name='image_data',
        ),
        migrations.AddField(
            model_name='aiactivity',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aithread',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraipreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aiactivity',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='aithread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proactivealert',
            name='alert_type',
            field=models.CharField(choices=[('weather', 'Weather'), ('event', 'Event'), ('security', 'Security')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proactivealert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiactivity',
            index=models.Index(fields=['thread', 'timestamp'], name='ai_aiactivi_thread__594dff_idx'),
        ),
        migrations.AddIndex(
            model_name='aithread',
            index=models.Index(fields=['user', '-updated_at'], name='ai_aithread_user_id_9d4873_idx'),
        ),
        migrations.AddIndex(
            model_name='proactivealert',
            index=models.Index(fields=['user', '-created_at'], name='ai_proactiv_user_id_99b979_idx'),
        ),
    ]
