# Generated by Django 6.0.2 on 2026-04-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_proactivealert_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiactivity',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
