# Generated by Django 6.0.2 on 2026-04-20 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('SAFETY', 'Safety'), ('LIFESTYLE', 'Lifestyle'), ('NAVIGATION', 'Navigation'), ('EXPERIENCE', 'Experience'), ('ACCESSIBILITY', 'Accessibility')], max_length=20)),
                ('sub_topics', models.JSONField(help_text="List of sub topics e.g ['scams', 'night safety']")),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_address', models.CharField(blank=True, max_length=255)),
                ('trust_score', models.IntegerField(default=0, help_text="Calculated from creator's trust score and tip engagement")),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('reports', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admins or trusted locals')),
                ('is_public', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden due to reports or moderation')),
                ('featured_until', models.DateTimeField(blank=True, help_text='Featured tips get priority', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-trust_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('INACCURATE', 'Inaccurate Information'), ('SPAM', 'Spam'), ('INAPPROPRIATE', 'Inappropriate Content'), ('DUPLICATE', 'Duplicate'), ('OUTDATED', 'Outdated')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
