# Generated by Django 6.0.2 on 2026-04-20 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipreport',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_records', to='tips.tip'),
        ),
        migrations.AddField(
            model_name='tipreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipupvote',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvote_records', to='tips.tip'),
        ),
        migrations.AddField(
            model_name='tipupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['category', '-trust_score'], name='tips_tip_categor_937a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['latitude', 'longitude'], name='tips_tip_latitud_cfe70d_idx'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['created_by', '-created_at'], name='tips_tip_created_da29ee_idx'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['is_public', 'is_hidden'], name='tips_tip_is_publ_d3822f_idx'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['trust_score'], name='idx_tip_trust'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['upvotes'], name='idx_tip_upvotes'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['created_at'], name='idx_tip_created'),
        ),
        migrations.AddIndex(
            model_name='tipreport',
            index=models.Index(fields=['tip', '-created_at'], name='tips_tiprep_tip_id_7a9dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='tipreport',
            index=models.Index(fields=['is_resolved', '-created_at'], name='tips_tiprep_is_reso_9e80bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tipreport',
            unique_together={('user', 'tip')},
        ),
        migrations.AddIndex(
            model_name='tipupvote',
            index=models.Index(fields=['tip', '-created_at'], name='tips_tipupv_tip_id_b3a721_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tipupvote',
            unique_together={('user', 'tip')},
        ),
    ]
