# Generated by Django 6.0.2 on 2026-04-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('TIP_CREATED', 'Tip Created'), ('TIP_UPVOTED', 'Tip Upvoted'), ('CHAT_HELPFUL', 'Chat Helpful'), ('VERIFIED_LOCAL', 'Verified Local'), ('MOMENT_LIKED', 'Moment Liked'), ('EXPERIENCE_BOOKED', 'Experience Booked'), ('SOS_RESOLVED', 'SOS Resolved')], max_length=50)),
                ('points_awarded', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassportBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='passport_badges/')),
                ('criteria_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PassportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('trust_score', models.IntegerField(db_index=True, default=0)),
                ('points', models.IntegerField(db_index=True, default=0)),
                ('level', models.IntegerField(db_index=True, default=1)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('VISIT', 'Visit Location'), ('POST_MOMENT', 'Post Moment'), ('SEND_MESSAGE', 'Send Message'), ('HELPFUL_TIP', 'Helpful Tip'), ('REPORT', 'Report Content'), ('VERIFICATION', 'Account Verification'), ('EXPERIENCE_CREATED', 'Experience Created'), ('SOS_RESPONSE', 'SOS Response'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment')], max_length=50)),
                ('points_change', models.IntegerField(help_text='Positive for gains, negative for losses')),
                ('balance_after', models.IntegerField(help_text="User's balance after this transaction")),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
