# Generated by Django 6.0.2 on 2026-04-20 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passportactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passportprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.passportbadge'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passportprofile',
            index=models.Index(fields=['user'], name='idx_passport_user'),
        ),
        migrations.AddIndex(
            model_name='passportprofile',
            index=models.Index(fields=['trust_score'], name='idx_passport_trust'),
        ),
        migrations.AddIndex(
            model_name='passportprofile',
            index=models.Index(fields=['points'], name='idx_passport_points'),
        ),
        migrations.AddIndex(
            model_name='passportprofile',
            index=models.Index(fields=['level'], name='idx_passport_level'),
        ),
        migrations.AddIndex(
            model_name='passportprofile',
            index=models.Index(fields=['created_at'], name='idx_passport_created'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['user', '-created_at'], name='passport_po_user_id_60c33e_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='passport_po_transac_389b49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
    ]
