# Generated by Django 6.0.2 on 2026-03-26 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, help_text='Watumiaji waliofuta ujumbe huu upande wao.', related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
