# Generated by Django 6.0.2 on 2026-04-20 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kilicaremoments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactionlog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_target_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kilicaremoment',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='target_moment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kilicaremoments.kilicaremoment'),
        ),
        migrations.AddField(
            model_name='momentcomment',
            name='moment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kilicaremoments.kilicaremoment'),
        ),
        migrations.AddField(
            model_name='momentcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='momentlike',
            name='moment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='kilicaremoments.kilicaremoment'),
        ),
        migrations.AddField(
            model_name='momentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedmoment',
            name='moment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kilicaremoments.kilicaremoment'),
        ),
        migrations.AddField(
            model_name='savedmoment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.AddIndex(
            model_name='kilicaremoment',
            index=models.Index(fields=['posted_by', '-created_at'], name='kilicaremom_posted__d675a8_idx'),
        ),
        migrations.AddIndex(
            model_name='kilicaremoment',
            index=models.Index(fields=['-trending_score', '-created_at'], name='kilicaremom_trendin_dedc42_idx'),
        ),
        migrations.AddIndex(
            model_name='kilicaremoment',
            index=models.Index(fields=['visibility', 'is_hidden'], name='kilicaremom_visibil_7ab555_idx'),
        ),
        migrations.AddIndex(
            model_name='kilicaremoment',
            index=models.Index(fields=['is_featured', '-created_at'], name='kilicaremom_is_feat_934807_idx'),
        ),
        migrations.AddIndex(
            model_name='kilicaremoment',
            index=models.Index(fields=['latitude', 'longitude'], name='kilicaremom_latitud_d43e75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='momentlike',
            unique_together={('user', 'moment')},
        ),
        migrations.AlterUniqueTogether(
            name='savedmoment',
            unique_together={('user', 'moment')},
        ),
    ]
