# Generated by Django 6.0.2 on 2026-05-12 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilicaremoments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kilicaremoment',
            name='background_music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moments', to='kilicaremoments.backgroundmusic'),
        ),
    ]
