# Generated by Django 6.0.2 on 2026-03-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localexperience',
            name='category',
            field=models.CharField(choices=[('Safari', 'Safari'), ('Local Food', 'Local Food'), ('Culture', 'Culture'), ('Night Life', 'Night Life')], default='Culture', max_length=50),
        ),
    ]
